### ISSUE TITLE
grep on macOS (10.13) fails - shows basic usage manual

### ISSUE THREAD

**Issue by anderseklov** [yuriyyakym/sitemap-urls#2]
The output of terminal on macOS 10.13.6 is the standard usage instructions for grep. Perhaps there is an issue with the grep regex?  Or perhaps the `tr` command turning line breaks into spaces? (unsure of the `<<<` syntax ([here-string](https://unix.stackexchange.com/a/80372)) in macOS this far back).

Terminal output:

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]

```

**Comment by yuriyyakym** [comment]
@anderseklov Thank you for reporting this!

The problem is that pre-installed macOS grep doesn't support `-P` flag (perl regexp), which was used before. I have replaced this grep with a direct perl usage.

Also added gzipped sitemaps support, like this one: https://developer.mozilla.org/sitemap.xml

Please let me know if it works now.

**Comment by anderseklov** [comment]
@yuriyyakym Thanks for the update. Works well now. Downloads big and nested `sitemap_index.xml` files with ease, well it takes a while, but does the trick!

**Note**: When fetching a Mozillas site from XML that links to gzip files embedded, the Readme.md's example:
`./sitemap-urls.sh https://developer.mozilla.org/sitemap.xml | grep -e .html$`

... downloads only 4 files, that all end with `/html` - not `.html`

Perhaps the `grep` is ignoring the `.` ?

I tried with `grep -e ".html$"`, thought it needed double quotes, but no dice. Again macos 10.13. And this is a top-level issue for me, not an issue with your main script.

**Comment by yuriyyakym** [comment]
@anderseklov sorry for bad example. It turns out that MDN doesn't have `.html` files in their sitemap anymore.

In regexp dot is a wildcard and it maches any character. If you want to match a literal dot only, you need to escape it with backslash.

I have updated the examples. Hope it helps.

**Comment by anderseklov** [comment]
@yuriyyakym I forgot the significance of the `.` I'm afraid. Remember it now from a recent app I made :). Thanks!
